version: '3.8'

services:
  review-read:
    container_name: review-read-service
    image: 090188239653.dkr.ecr.ap-northeast-2.amazonaws.com/review-read-service
    volumes:
      - /home/ubuntu/config/review-read/application.yml:/config/review-read/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/review-read/application.yml
    ports:
      - "8086:8086"
    env_file:
      - /home/ubuntu/env/.env.review-read
    networks:
      - backend

networks:
  backend:
    external: true